### ISSUE TITLE
simplemdm_customprofile.mobileconfig should take data not a file path

### ISSUE THREAD

**Issue by remilapeyre** [DavidKrau/terraform-provider-simplemdm#12]
The [mobileconfig](https://registry.terraform.io/providers/DavidKrau/simplemdm/latest/docs/resources/customprofile#mobileconfig) of the [simplemdm_customprofile](https://registry.terraform.io/providers/DavidKrau/simplemdm/latest/docs/resources/customprofile) resource should take the content of the mobileconfig file not a path to it. This would make it possible to write:

```terraform
resource "simplemdm_customprofile" "myprofile" {
  name                   = "My First profiles"
  mobileconfig           = templatefile("./profiles/profile.mobileconfig", { foo = "bar" })
  filesha                = sha256(templatefile("./profiles/profile.mobileconfig", { foo = "bar" }))
  userscope              = true
  attributesupport       = true
  escapeattributes       = true
  reinstallafterosupdate = false
}
```

which is not currently possible.

I think the `filesha` argument may also be removed because it can be computed in the provider from the `mobileconfig` one.

**Comment by DavidKrau** [comment]
Hey,

these changed sounds reasonable. I will look into this next week (or maybe some free evening in hotel room) as i am traveling this week a bit and implement them.

Changes will need to be done to resource and also to client to accept string and send it as multipart request.

David

**Comment by remilapeyre** [comment]
I just understood why there is the `filesha` argument. It's to trigger the update when the file changes right? If so we won't need it once we take the content of the file directly indeed.

**Comment by remilapeyre** [comment]
FYI I thing there is the same issue with `simplemdm_script`.

**Comment by DavidKrau** [comment]
Hey,
yes i am aware that scripts are facing same "issue".

SHA was used to get change compare to SimpleMDM profile/change in file. 

I really hope that i will fix it this week to be consistent cross provider.

**Comment by DavidKrau** [comment]
Completed in https://github.com/DavidKrau/terraform-provider-simplemdm/releases/tag/v0.1.15
