### ISSUE TITLE
Wrong configuration management for the provider

### ISSUE THREAD

**Issue by remilapeyre** [DavidKrau/terraform-provider-simplemdm#7]
The configuration management at https://github.com/DavidKrau/terraform-provider-simplemdm/blob/main/provider/provider.go#L78-L96 is wrong, the error message reference the wrong attribute.

I also think that it does not defaults properly to the environment variables.

**Comment by DavidKrau** [comment]
Wow this part of my code is soo ugly....

I see the issue and will fix it during today. But anyway currently env variables are working as expected. ENV variables are 

SIMPLEMDM_HOST and SIMPLEMDM_APIKEY (will double check it in documentation later).

First it is trying to load ENV variables lines https://github.com/DavidKrau/terraform-provider-simplemdm/blob/main/provider/provider.go#L104-L105

If there are variables set in config it will overwrite ENV variables by config https://github.com/DavidKrau/terraform-provider-simplemdm/blob/main/provider/provider.go#L107-L114

and finally check if we have all needed details, in case we dont have host in ENV variable or in config it default to a.simplemdm.com If there are variables set in config it will overwrite ENV variables by config https://github.com/DavidKrau/terraform-provider-simplemdm/blob/main/provider/provider.go#L117-L119 and if API key is not present we will get error https://github.com/DavidKrau/terraform-provider-simplemdm/blob/main/provider/provider.go#L121-L133

**Comment by remilapeyre** [comment]
> First it is trying to load ENV variables lines https://github.com/DavidKrau/terraform-provider-simplemdm/blob/main/provider/provider.go#L104-L105

At that point you already returned from `Configure()` at https://github.com/DavidKrau/terraform-provider-simplemdm/blob/main/provider/provider.go#L99.

If you want I think @rayennh is already working on a fix.

**Comment by DavidKrau** [comment]
That whole part between lines https://github.com/DavidKrau/terraform-provider-simplemdm/blob/main/provider/provider.go#L78-L99 applies only if you would use TF reference for apikey or host as example if you would use: 

```
resource "random_string" "example" {}

provider "simplemdm" {
  apikey = random_string.example.result
}
```


if `random_string.example.result` would be unknown (TF doesnt have graph dependency) it will return error on line  https://github.com/DavidKrau/terraform-provider-simplemdm/blob/main/provider/provider.go#L99

It has nothing to do with Environmental variables. Yes errors there were wrong and corrected together with error messages.

Also from my test i dont have any issue to run lets say `SIMPLEMDM_APIKEY=abcd  terraform plan` and that works as expected.

**Comment by DavidKrau** [comment]
As reference: 

https://developer.hashicorp.com/terraform/plugin/framework/providers#unknown-values

**Comment by remilapeyre** [comment]
Yes, I read that too quickly it seems like it is just the error message that needs to be fixed. I'm not sure why it wasn't working during our tests but it must have been something else.

**Comment by DavidKrau** [comment]
Cool. Thanks for clarifying. Will publish provider with fixed error messages and one broken check later today. Which is in this branch https://github.com/DavidKrau/terraform-provider-simplemdm/tree/7-wrong-configuration-management-for-thre-provider

Closing this issue and done.
